@baseTestUrl = http://localhost:4004

### ------------------------------------------------------------------------
### Test getJsonData Endpoint ----------------------------------------------
GET {{baseTestUrl}}/xlsxf/getSampleJsonData()
